### ISSUE TITLE
Specific error message checks in input unit tests

### ISSUE THREAD

**Issue by jonathanishhorowicz** [ImperialCollegeLondon/epidemia#1]
The current input checking tests do not check the error messages, which could hide other problems. This will require removing `$` from the error messages.

**Comment by jscott6** [comment]
@jonathanishhorowicz Just checking if this issue is closed now? Think I saw some tests which do this

**Comment by jonathanishhorowicz** [comment]
I have been adding it to new tests, where possible, but the tests that this issue refers to haven't been changed.

**Comment by jonathanishhorowicz** [comment]
I will add the messages to the remaining tests this week - turns out I was just using regexp in the wrong way!
