### ISSUE TITLE
Partial pooling for infection ascertainment rate(IAR) in the model

### ISSUE THREAD

**Issue by s-mishra** [ImperialCollegeLondon/epidemia#39]
Right now we estimate IAR differently for each individual lowest sub-group. It would be ideal to have an option to specify partial pooling for IAR like we do for covariates.

**Comment by jscott6** [comment]
This is a good idea. Replicating the full 'machinery' that we use for the regression for Rt is difficult. As a first step, we can allow different offsets for each group (i.e. different base IFR/IAR), but make all regression parameters pooled.
