### ISSUE TITLE
install_github doesn't include documentation

### ISSUE THREAD

**Issue by wwiecek** [ImperialCollegeLondon/epidemia#43]
Sorry, maybe I'm missing an obvious alternative and/or this was intended, but just in case: for non-dev users who will use `install_github()` route recommended on your website, the package repo does not include man/ files. So only users with some working knowledge of git/package development can get the documentation (by cloning -> `devtools::document()` and then building).

**Comment by jscott6** [comment]
Thanks a lot for this - the *.Rd files are currently in .gitignore as they are generated by roxygen. You're right that as a consequence `devtools::install_github()` will not install help pages. We'll either check in the doc files or add further installation instructions with the next release.
