### ISSUE TITLE
EuropeCovid example not converging & doc missing

### ISSUE THREAD

**Issue by annecori** [ImperialCollegeLondon/epidemia#50]
I tried to run the example code on EuropeCovid data from here: 
[https://imperialcollegelondon.github.io/epidemia/](https://imperialcollegelondon.github.io/epidemia/)
and I get warnings of non convergence despite having used the same random seed as in the example and exactly the same parameters. 

Could you please perhaps edit the example so it converges? 

Also, it would be really nice if you could document the functions in the package? I know there is help in the vignettes but it would be helpful to also be able to use `?epirt` for example to get help on specific functions. 

Thanks very much!

**Comment by jscott6** [comment]
Thanks for reaching out and alerting us to this. Can confirm that I see the same convergence warnings when running this example again. This appears to be related to one chain sampling faster than the others. I will update the example to fix this. In the meantime, using 
`args$sampling_args <- list(iter=2e3, seed=12345, control=list(adapt_delta = 0.9))`
`
in place of the current `sampling_args` should address this. You will still get warnings about max_treedepth - but this is just an efficiency problem. Warnings about ESS can be dealt with by increasing `iter`.

Function documentation can be found [here](https://imperialcollegelondon.github.io/epidemia/reference/index.html). We currently do not check in the documentation as these are generated files. If you would like documentation locally, for now you can clone the directory and run `devtools::document()` before installing the local version of the package. We are planning to include documentation in the repo in the next release (issue #43).
